# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebase_crashlytics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebase_crashlytics
pod 'Firebase/Core'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'
  target 'firebase_crashlyticsTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase'
  end

  target 'firebase_crashlyticsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
